"""created at column

Revision ID: d316f025ec73
Revises: 1c2a6693cee6
Create Date: 2024-11-12 21:31:39.480710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd316f025ec73'
down_revision = '1c2a6693cee6'
branch_labels = None
depends_on = None


def upgrade():
    op.add_column('listings', sa.Column('created_at', sa.DateTime(), nullable=True))  # Step 1
    op.execute("UPDATE listings SET created_at = CURRENT_TIMESTAMP")  # Step 2
    op.alter_column('listings', 'created_at', nullable=False)  # Step 3

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.drop_column('listings', 'created_at')

    # ### end Alembic commands ###
